# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

require_relative 'subutai_hooks.rb'
require_relative 'subutai_net.rb'
require_relative 'subutai_config.rb'

SubutaiConfig.load_config(ARGV[0])
SubutaiConfig.print

Vagrant.require_version '>= 2.0.1'

Vagrant.configure('2') do |config|
  config.vm.box = 'subutai/nat'
  config.ssh.username = 'subutai'
  config.ssh.password = 'ubuntai'

  config.vm.network 'private_network', :type => 'dhcp', nic_type: 'virtio'
  config.vm.network 'forwarded_port', guest: 8443, host: SubutaiConfig.get('CONSOLE_PORT')

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = SubutaiConfig.get(:SUBUTAI_RAM)
    vb.cpus = SubutaiConfig.get(:SUBUTAI_CPU)

    # To avoid the Sierra bug let's turn off things we do not need
    # See here: https://github.com/monetate/ectou-export/issues/5
    vb.customize ['modifyvm', :id, '--audio', 'none']
    vb.customize ['modifyvm', :id, '--uart1', 'off']
    vb.customize ['modifyvm', :id, '--uart2', 'off']
    vb.customize ['modifyvm', :id, '--uart3', 'off']
    vb.customize ['modifyvm', :id, '--uart4', 'off']

    # This box is used for multi-vm configurations and to reduce disk usage
    # with possibly several virtual machines, we need to use linked clones.
    vb.linked_clone = true
  end

  unless SubutaiConfig.get(:_ALT_SNAP).nil?
    config.vm.provision 'file', source: SubutaiConfig.get(:_ALT_SNAP), destination: '$HOME/subutai.snap'
  end

  unless SubutaiConfig.get(:_ALT_MANAGEMENT).nil?
    config.vm.provision 'file', source: SubutaiConfig.get(:_ALT_MANAGEMENT), destination: '$HOME/subutai.management'
  end

  config.vm.provision 'shell',
                      env: SubutaiConfig.config,
                      # path: 'https://raw.githubusercontent.com/subutai-io/packer/master/private_nat/provisioning_scripts/en/provisioner.sh'
                      path: '/Users/akarasulu/Projects/subutai.io/packer/nat/provisioning_scripts/en/provisioner.sh'
end
