#!/bin/bash

### BEGIN INIT INFO
# Provides:             crowd
# Required-Start:       $remote_fs $syslog $network
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Start Crowd daemon at boot time
# Description:          Enable Crowd service provided by Crowd daemon.
### END INIT INFO

. /home/vagrant/atlassian/.atlassianrc
. /home/vagrant/atlassian/crowd/.crowdrc

RUN_AS_USER=vagrant
CATALINA_HOME=/home/vagrant/atlassian/crowd/default


start() {
        echo "Starting Crowd: "
        if [ "x$USER" != "x$RUN_AS_USER" ]; then
          su - $RUN_AS_USER -c "$CATALINA_HOME/start_crowd.sh"
        else
          $CATALINA_HOME/start_crowd.sh
        fi

        echo "done."
}
stop() {
        echo "Shutting down Crowd: "
        if [ "x$USER" != "x$RUN_AS_USER" ]; then
          su - $RUN_AS_USER -c "$CATALINA_HOME/stop_crowd.sh"
        else
          $CATALINA_HOME/stop_crowd.sh
        fi
        echo "done."
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        sleep 10
        #echo "Hard killing any remaining threads.."
        #kill -9 `cat $CATALINA_HOME/work/catalina.pid`
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
esac

exit 0
