#!/bin/bash

function vagrant_change() {
  echo `cat /etc/network/interfaces | grep VAGRANT`
}

function change_handler() {
  action="$1"
  MD5="`md5sum /etc/network/interfaces`"
  MD5_BACKUP="`md5sum /etc/network/virtualbox-interfaces`"

  if [ "$MD5" = "$MD5_BACKUP" ]; then
    return
  elif [ -n "$(vagrant_change)" ]; then
    echo Vagrant mods detected: replacing, and restarting networking
    cp /etc/network/virtualbox-interfaces /etc/network/interfaces
    systemctl restart networking.service
  fi
}

# Settings
TIMEOUT="30"

change_handler;
while true; do
  inotifywait /etc/network/interfaces -t $TIMEOUT -e create -e modify |
  while read path action file; do
    change_handler "$action";
  done
done
