# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

unless Vagrant.has_plugin?('vagrant-subutai')
  raise 'Vagrant Subutai Plugin required: vagrant plugin install vagrant-subutai'
end

unless Vagrant.has_plugin?('vagrant-vmware-desktop')
  raise 'Vagrant Libvirt Plugin required: vagrant plugin install vagrant-vmware-desktop'
end

require 'vagrant-subutai'
require 'pry-byebug' # TODO remove on production

SubutaiConfig.bridged!
SubutaiConfig.logging!(:debug)

SubutaiConfig.load_config(ARGV[0], :vmware)
SubutaiConfig.print

Vagrant.require_version '>= 2.0.1'

Vagrant.configure('2') do |config|

  config.vm.box = 'subutai/stretch'
  url = SubutaiConfig.url_of_cdn
  owner = '43d722f2c81bcd5159de5e5a482613b046c548b6'
  artifact_name = 'vagrant-subutai-stretch-vmware-workstation.box'
  #config.vm.box_url = url + '/raw/download?id=' + SubutaiConfig.get_latest_id_artifact(owner,artifact_name) # TODO only vagrant up get info id from cdn
  config.ssh.username = 'subutai'

  config.vm.base_mac = SubutaiConfig.get(:_BASE_MAC)

  # Second Bridged Interface enp???
  unless SubutaiConfig.get(:BRIDGE).nil?
    config.vm.network 'public_network', :type => 'dhcp', :adapter => 1
  end


  if SubutaiConfig.get(:SUBUTAI_PEER)
    config.vm.network 'forwarded_port', guest: 8443, host: SubutaiConfig.get(:_CONSOLE_PORT), auto_correct: true
  end

  # Third Host-Only Interface enp???
 # config.vm.network 'private_network', :type => 'dhcp', :adapter => 3


  config.vm.synced_folder ".", "/vagrant", type: "rsync"

=begin
  config.vm.provider 'libvirt' do |libvirt|
    libvirt.driver = 'kvm'
    libvirt.connect_via_ssh = false
    libvirt.username = 'subutai'
    libvirt.storage_pool_name = 'default'

    libvirt.memory = SubutaiConfig.get(:SUBUTAI_RAM)
    libvirt.cpus = SubutaiConfig.get(:SUBUTAI_CPU)

    if ARGV[0] == 'up'
      has_grow, grow_by = SubutaiDisk.has_grow

      if has_grow
        size = SubutaiDisk.libvirt_size(grow_by)

        STDOUT.puts  "\e[33mDisk size is growing by #{grow_by} gb.\e[0m"

        libvirt.storage :file, :size => size, :cache => "none"

        SubutaiDisk.save_conf(grow_by)
      end
    end
  end
=end
  config.vm.provider "vmware_desktop" do |v|
    v.linked_clone = false
    v.vmx["memsize"] = SubutaiConfig.get(:SUBUTAI_RAM)
    v.vmx["numvcpus"] = SubutaiConfig.get(:SUBUTAI_CPU)
    v.vmx["ethernet0.pcislotnumber"] = "33"
  end

  config.vm.provision 'shell', env: SubutaiConfig.config, inline: <<-SHELL
    echo "SUBUTAI_VAGRANT_VERSION=$VERSION"   >> /etc/environment
    echo "SUBUTAI_BRIDGE_IFACE=eth1"        >> /etc/environment
    echo "SUBUTAI_NAT_IFACE=eth0"           >> /etc/environment
    #echo "SUBUTAI_HOST_IFACE=enp0s9"          >> /etc/environment

    if [ -n "$PASSWORD_OVERRIDE" ]; then
      usermod --password $(echo "$PASSWORD_OVERRIDE" | openssl passwd -1 -stdin) subutai
    fi
  SHELL

  unless SubutaiConfig.get(:AUTHORIZED_KEYS).nil?
    config.vm.provision 'file', source: SubutaiConfig.get(:AUTHORIZED_KEYS), destination: '/tmp/authorized_keys'

    config.vm.provision 'shell', inline: <<-SHELL
      mkdir -p /root/.ssh
      cat /tmp/authorized_keys >> /root/.ssh/authorized_keys
      chmod 600 /root/.ssh/authorized_keys
      chmod 700 /root/.ssh

      mkdir -p /home/subutai/.ssh
      cat /tmp/authorized_keys >> /home/subutai/.ssh/authorized_keys
      chown subutai:subutai /home/subutai/.ssh/authorized_keys
      chmod 600 /home/subutai/.ssh/authorized_keys
      chmod 700 /home/subutai/.ssh
      chown subutai:subutai /home/subutai/.ssh
    SHELL
  end

  if SubutaiConfig.provision_snap?
    config.vm.provision 'file', source: SubutaiConfig.get(:_ALT_SNAP), destination: '$HOME/subutai.snap'
    SubutaiConfig.snap_provisioned!
  end

  if SubutaiConfig.provision_management?
    config.vm.provision 'file', source: SubutaiConfig.get(:_ALT_MANAGEMENT), destination: '$HOME/subutai.management'
    SubutaiConfig.management_provisioned!
  end

  config.vm.provision 'shell', env: SubutaiConfig.config,
                      path: 'https://raw.githubusercontent.com/subutai-io/packer/master/provisioning/en/provisioner.sh'

  has_grow, grow_by = SubutaiDisk.has_grow

  if has_grow
    config.vm.provision "shell", run: "always", env: {DISK_SIZE: grow_by.to_i},
                        path: 'https://raw.githubusercontent.com/subutai-io/packer/master/provisioning/en/subutai_disk.sh'
  end

  config.vm.provision :blueprint
end