# -*- mode: ruby -*-
# vi: set ft=ruby :

def new_mac() 
    sequence :mac do |n|
    12.times.map { num = (0..15).to_a.sample; num.to_s(16) }.each_slice(2).to_a.map { |arr| arr.join('') }.join(":").upcase
  end
end

Vagrant.require_version ">= 2.0.0"

Vagrant.configure("2") do |config|
  config.vm.box = "subutai/stretch"
  config.ssh.username = "subutai"
  config.ssh.password = "ubuntai"
  config.ssh.port = "4567"

  config.vm.network "public_network", :type => 'dhcp', :adapter => 1, nic_type: "virtio"
  config.vm.network "private_network", :type => 'dhcp', :adapter => 3, nic_type: "virtio"

  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2
    vb.name = "subutai-stretch"

    # eth1 nat interface configuration
    vb.customize ["modifyvm", :id, "--nic2", "nat"]
    vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
    vb.customize ["modifyvm", :id, "--natpf2", "ssh,tcp,127.0.0.1,4567,,22"]
    vb.customize ["modifyvm", :id, "--natpf2", "https,tcp,127.0.0.1,9999,,8443"]

    # To avoid the Sierra bug let's turn off things we do not need
    # See here: https://github.com/monetate/ectou-export/issues/5
    vb.customize ["modifyvm", :id, "--audio", "none"]

    vb.customize ["modifyvm", :id, "--uart1", "off"]
    vb.customize ["modifyvm", :id, "--uart2", "off"]
    vb.customize ["modifyvm", :id, "--uart3", "off"]
    vb.customize ["modifyvm", :id, "--uart4", "off"]

    # console output for debugging: remove first uart1 disabling line above
    # vb.customize [ "modifyvm", :id, "--uart1", "0x3F8", "4" ]
    # vb.customize [ "modifyvm", :id, "--uartmode1", "file", File.join(Dir.pwd, vb.name + "-console.log") ]

    # only for dev and master
    vb.linked_clone = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    # Neet to wait for network: reset on Vagrant up changes
    while true; do
      ping -c 1 mit.edu &> /dev/null;
      if [ ! "$?" = "0" ]; then
        echo "Configuring interfaces ..."
        sleep 5;
      else
        break;
      fi;
    done

    echo "Finding nearest apt mirror"
    country=`curl -s ipinfo.io | grep country | awk -F ':' '{print $2}' | sed -e 's/[", ]//g'`

    if [ "KG" = "$country" ]; then
      country=KZ
    fi

    netselect-apt -c $country &> /dev/null
    if [ ! "$?" = "0" ]; then
      netselect-apt -c US &> /dev/null
    fi

    if [ -f "sources.list" ]; then
      mv sources.list /etc/apt/sources.list
    fi

    echo "Installing Subutai Snap ..."
    snap install subutai --devmode --beta

    echo "Mounting container storage ..."
    /snap/subutai/current/bin/btrfsinit /dev/mapper/main-btrfs &> /dev/null

    echo "SUCCESS: Debian Stretch resource host (RH) ready!"
    echo 'Want to convert this RH into a peer?'
    echo "Step 1: Use 'vagrant ssh' to get into the RH"
    echo "Step 2: Use 'sudo /snap/bin/subutai import management' to install the peer"
    echo "Step 3: Hit https://localhost:9999 on Chrome with Subutai extension"
    echo "Default user credentials: 'admin' / 'secret'"
    echo "Welcome to the horde!"
  SHELL
end
