Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.network "forwarded_port", guest: 3142, host: 3142
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vbguest.auto_update = false
  config.vbguest.no_remote = true

  config.vm.provision "shell", inline: <<-SHELL
    DEBIAN_FRONTEND=noninteractive apt-get update
    DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
    DEBIAN_FRONTEND=noninteractive apt-get install apt-cacher-ng
  SHELL
end
