# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 2.0.1"

Vagrant.configure("2") do |config|
  config.vm.box = "subutai/nobridge"
  config.ssh.username = "subutai"
  config.ssh.password = "ubuntai"

  config.vm.network "private_network", :type => 'dhcp', nic_type: "virtio"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 2

    # To avoid the Sierra bug let's turn off things we do not need
    # See here: https://github.com/monetate/ectou-export/issues/5
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--uart1", "off"]
    vb.customize ["modifyvm", :id, "--uart2", "off"]
    vb.customize ["modifyvm", :id, "--uart3", "off"]
    vb.customize ["modifyvm", :id, "--uart4", "off"]

    vb.linked_clone = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "Installing Subutai Snap ..."
    snap install subutai --devmode --beta

    echo "Mounting container storage ..."
    /snap/subutai/current/bin/btrfsinit /dev/mapper/main-btrfs &> /dev/null

    echo "SUCCESS: Debian Stretch resource host (RH) ready!"
    echo 'Want to convert this RH into a peer?'
    echo "Step 1: Use 'vagrant ssh' to get into the RH"
    echo "Step 2: Use 'sudo /snap/bin/subutai import management' to install the peer"
    echo "Step 3: Hit https://localhost:9999 on Chrome with Subutai extension"
    echo "Default user credentials: 'admin' / 'secret'"
    echo "Welcome to the horde!"
  SHELL
end

