# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

require_relative 'subutai_hooks.rb'
require_relative 'subutai_net.rb'
require_relative 'subutai_config.rb'

SubutaiConfig.bridged!
SubutaiConfig.logging!(:debug)

SubutaiConfig.load_config(ARGV[0], :virtualbox)
SubutaiConfig.print

Vagrant.require_version '>= 2.0.1'

Vagrant.configure('2') do |config|
  config.vm.box = 'subutai/lan-ubuntu'
  config.ssh.username = 'subutai'

  # Need to override packer's base_mac setting
  config.vm.base_mac = SubutaiConfig.get(:_BASE_MAC)

  # We need to find the SSH port so we can use it - vagrant should manage this automatically now
  # config.ssh.port = SubutaiConfig.get(:_SSH_PORT)

  # Second Bridged Interface enp???
  if SubutaiConfig.get(:BRIDGE).nil?
    config.vm.network 'public_network', :type => 'dhcp', :adapter => 2, nic_type: 'virtio'
  else
    config.vm.network 'public_network', :type => 'dhcp', :adapter => 2, nic_type: 'virtio',
                      :bridge => SubutaiConfig.get(:BRIDGE)
  end

  # Third Host-Only Interface enp???
  config.vm.network 'private_network', :type => 'dhcp', :adapter => 3, nic_type: 'virtio'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = SubutaiConfig.get(:SUBUTAI_RAM)
    vb.cpus = SubutaiConfig.get(:SUBUTAI_CPU)

    # To avoid the Sierra bug let's turn off things we do not need
    # See here: https://github.com/monetate/ectou-export/issues/5
    vb.customize ['modifyvm', :id, '--audio', 'none']
    vb.customize ['modifyvm', :id, '--uart1', 'off']
    vb.customize ['modifyvm', :id, '--uart2', 'off']
    vb.customize ['modifyvm', :id, '--uart3', 'off']
    vb.customize ['modifyvm', :id, '--uart4', 'off']

    # only for dev and master
    vb.linked_clone = true
  end

  config.vm.provision 'shell', inline: <<-SHELL
    echo "SUBUTAI_VAGRANT_VERSION=$VERSION"   >> /etc/environment
    echo "SUBUTAI_BRIDGE_IFACE=enp0s8"        >> /etc/environment
    echo "SUBUTAI_NAT_IFACE=enp0s3"           >> /etc/environment
    echo "SUBUTAI_HOST_IFACE=enp0s9"          >> /etc/environment
  SHELL

  if SubutaiConfig.provision_snap?
    config.vm.provision 'file', source: SubutaiConfig.get(:_ALT_SNAP), destination: '$HOME/subutai.snap'
    SubutaiConfig.snap_provisioned!
  end

  if SubutaiConfig.provision_management?
    config.vm.provision 'file', source: SubutaiConfig.get(:_ALT_MANAGEMENT), destination: '$HOME/subutai.management'
    SubutaiConfig.management_provisioned!
  end

  config.vm.provision 'shell', env: SubutaiConfig.config,
    path: 'https://raw.githubusercontent.com/subutai-io/packer/master/provisioning/en/provisioner.sh'
end
