# -*- mode: ruby -*-
# vi: set ft=ruby :

rrequire 'fileutils'

require_relative 'hooks.rb'
require_relative 'network.rb'
require_relative 'subconf.rb'

SubConf.load     # <<- loads from subutai.yaml, if it exists, then the env
                 # vv- set the alternative snap if available or via hook
SubConf.put('ALT_SNAP', snap_handler(SubConf.get 'SUBUTAI_SNAP'))
                 # vv- set the alternative management template if available or via hook
SubConf.put('ALT_MANAGEMENT', management_handler(SubConf.get 'SUBUTAI_MAN_TMPL'))
                 # vv- set the console port
SubConf.put('CONSOLE_PORT', find_port(SubConf.get('DESIRED_PORT'), 'console', 'virtualbox'))
SubConf.print

# everything blow here is the usual vagrant configurations
Vagrant.require_version ">= 2.0.1"
Vagrant.configure("2") do |config|
  config.vm.box = "subutai/private_nat"
  config.ssh.username = "subutai"
  config.ssh.password = "ubuntai"

  config.vm.network "private_network", :type => 'dhcp', nic_type: "virtio"
  config.vm.network "forwarded_port", guest: 8443, host: SubConf.get('CONSOLE_PORT')

  config.vm.provider "virtualbox" do |vb|
    vb.memory = SubConf.get('SUBUTAI_RAM')
    vb.cpus = SubConf.get('SUBUTAI_CPU')

    # To avoid the Sierra bug let's turn off things we do not need
    # See here: https://github.com/monetate/ectou-export/issues/5
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.customize ["modifyvm", :id, "--uart1", "off"]
    vb.customize ["modifyvm", :id, "--uart2", "off"]
    vb.customize ["modifyvm", :id, "--uart3", "off"]
    vb.customize ["modifyvm", :id, "--uart4", "off"]

    vb.linked_clone = true
  end

  if ! SubConf.get('ALT_SNAP').nil? then
    config.vm.provision "file", source: "#{SubConf.get('ALT_SNAP')}", destination: "$HOME/subutai.snap"
  end

  if ! SubConf.get('ALT_MANAGEMENT').nil? then
    config.vm.provision "file", source: "#{SubConf.get('ALT_MANAGEMENT')}", destination: "$HOME/subutai.management"
  end

  config.vm.provision "shell", env: {
      "CONSOLE_PORT"     => "#{SubConf.get 'CONSOLE_PORT'}",
      "ALLOW_INSECURE"   => "#{SubConf.get 'ALLOW_INSECURE'}",    
      "SUBUTAI_ENV"      => "#{SubConf.get 'SUBUTAI_ENV'}",      
      "SUBUTAI_PEER"     => "#{SubConf.get 'SUBUTAI_PEER'}",      
      "SUBUTAI_SNAP"     => "#{SubConf.get 'SUBUTAI_SNAP'}",      
      "SUBUTAI_DESKTOP"  => "#{SubConf.get 'SUBUTAI_DESKTOP'}",      
      "SUBUTAI_MAN_TMPL" => "#{SubConf.get 'SUBUTAI_MAN_TMPL'}",      
      "ALT_SNAP"         => "#{SubConf.get 'ALT_SNAP'}",      
      "ALT_MANAGEMENT"   => "#{SubConf.get 'ALT_MANAGEMENT'}",      
      "APT_PROXY_URL"    => "#{SubConf.get 'APT_PROXY_URL'}",      
      }, path: "https://raw.githubusercontent.com/subutai-io/packer/master/private_nat/provisioning_scripts/en/provisioner.sh"
      # }, path: "/Users/akarasulu/Projects/subutai.io/packer/private_nat/provisioning_scripts/en/provisioner.sh"
end


